import type { Metadata } from "next";
import { locales, localeDirections, type Locale } from "@/lib/i18n/config";
import { notFound } from "next/navigation";
import "../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return locales.map((locale) => ({ lang: locale }));
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: string }>;
}>) {
  const { lang } = await params;

  if (!locales.includes(lang as Locale)) {
    notFound();
  }

  const direction = localeDirections[lang as Locale];

  return (
    <html lang={lang} dir={direction}>
      <body className="antialiased">{children}</body>
    </html>
  );
}
